# Generated by Django 5.2.3 on 2025-06-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('stripe_public_key', models.CharField(max_length=255)),
                ('stripe_secret_key', models.CharField(max_length=255)),
            ],
        ),
    ]
