# Generated by Django 5.2.3 on 2025-07-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_city_alter_order_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='products_name',
            field=models.CharField(default='Product List', max_length=100),
        ),
    ]
